def Books():
    books = [
        {
            'id': 1,
            'isbn': '0399255373',
            'cover': 'crayons-quit.jpg',
            'title':'The Day the Crayons Quit',
            'genre_id': 4,
            'genre': 'Children\'s Books',
            'blurb':'Inner cover content will go here, a tale of struggle, love, and incompetence with a bittersweet resolution, this is definitely the book you should buy your mom for mother\'s day or whatever',
            'author_id': 1,
            'author': 'Drew Daywalt',
            'year_published': 2013
        },
        {
            'id': 2,
            'isbn': '0765378388',
            'cover': 'crayons-quit.jpg',
            'title':'The Calculating Stars: A Lady Astronaut Novel',
            'genre_id': 18,
            'genre': 'Science Fiction',
            'blurb':'Inner cover content will go here, a tale of struggle, love, and incompetence with a bittersweet resolution, this is definitely the book you should buy your mom for mother\'s day or whatever',
            'author_id': 2,
            'author': 'Mary Robinette Kowal',
            'year_published': 2018
        },
        {
            'id': 3,
            'isbn': '1476753830',
            'cover': 'crayons-quit.jpg',
            'title':'Salt, Fat, Acid, Heat: Mastering the Elements of Good Cooking',
            'genre_id': 6,
            'genre': 'Cookbooks',
            'blurb':'Inner cover content will go here, a tale of struggle, love, and incompetence with a bittersweet resolution, this is definitely the book you should buy your mom for mother\'s day or whatever',
            'author_id': 3,
            'author': 'Samin Nosrat',
            'year_published': 2017
        },
        {
            'id': 4,
            'isbn': '1416590323',
            'cover': 'crayons-quit.jpg',
            'title':'Frederick Douglass: Prophet of Freedom',
            'genre_id': 2,
            'genre': 'Biography',
            'blurb':'Inner cover content will go here, a tale of struggle, love, and incompetence with a bittersweet resolution, this is definitely the book you should buy your mom for mother\'s day or whatever',
            'author_id': 4,
            'author': 'David W. Blight',
            'year_published': 2020
        },
        {
            'id': 5,
            'isbn': '0297859382',
            'cover': 'crayons-quit.jpg',
            'title':'Gone Girl',
            'genre_id': 13,
            'genre': 'Mystery & Thriller',
            'blurb':'Inner cover content will go here, a tale of struggle, love, and incompetence with a bittersweet resolution, this is definitely the book you should buy your mom for mother\'s day or whatever',
            'author_id': 5,
            'author': 'Gillian Flynn',
            'year_published': 2012
        },
        {
            'id': 6,
            'isbn': '0984782850',
            'cover': 'crayons-quit.jpg',
            'title':'Cracking the Coding Interview: 189 Programming Questions and Solutions',
            'genre_id': 3,
            'genre': 'Business',
            'blurb':'Inner cover content will go here, a tale of struggle, love, and incompetence with a bittersweet resolution, this is definitely the book you should buy your mom for mother\'s day or whatever',
            'author_id': 6,
            'author': 'Gayle Laakmann McDowell',
            'year_published': 2015
        },
        {
            'id': 7,
            'isbn': '1608468569',
            'cover': 'crayons-quit.jpg',
            'title': 'Electric Arches',
            'genre_id': 15,
            'genre': 'Poetry',
            'cover-img-url':'../static/electric-arches.jpg',
            'blurb':'Inner cover content will go here, a tale of struggle, love, and incompetence with a bittersweet resolution, this is definitely the book you should buy your mom for mother\'s day or whatever',
            'author_id': 7,
            'author': 'Eve L. Ewing',
            'year_published': 2017
        },
        {
            'id': 8,
            'isbn': '1512308056',
            'cover': 'crayons-quit.jpg',
            'title': 'Frankenstein',
            'genre_id': 5,
            'genre': 'Classics',
            'blurb':'Inner cover content will go here, a tale of struggle, love, and incompetence with a bittersweet resolution, this is definitely the book you should buy your mom for mother\'s day or whatever',
            'author_id': 8,
            'author': 'Mary Shelley',
            'year_published': 1818
        },
        {
            'id': 9,
            'isbn': '0141439518',
            'cover': 'crayons-quit.jpg',
            'title': 'Pride and Prejudice',
            'genre_id': 5,
            'genre': 'Romance',
            'blurb':'Inner cover content will go here, a tale of struggle, love, and incompetence with a bittersweet resolution, this is definitely the book you should buy your mom for mother\'s day or whatever',
            'author_id': 9,
            'author': 'Jane Austen',
            'year_published': 1813
        },
        {
            'id': 10,
            'isbn': '1615190614',
            'cover': 'fok.jpg',
            'title':'Forks Over Knives―The Cookbook: Over 300 Recipes for Plant-Based Eating All Through the Year',
            'genre_id': 6,
            'genre': 'Cookbooks',
            'blurb':'Inner cover content will go here, a tale of struggle, love, and incompetence with a bittersweet resolution, this is definitely the book you should buy your mom for mother\'s day or whatever',
            'author_id': 10,
            'author': 'Del Sroufe',
            'year_published': 2012
        },
        {
            'id': 11,
            'isbn': '1592408990',
            'cover': 'wine.jpg',
            'title':'Wine Folly: The Essential Guide to Wine',
            'genre_id': 6,
            'genre': 'Cookbooks',
            'blurb':'Inner cover content will go here, a tale of struggle, love, and incompetence with a bittersweet resolution, this is definitely the book you should buy your mom for mother\'s day or whatever',
            'author_id': 11,
            'author': 'Madeline Puckette',
            'year_published': 2015
        },
    ]
    return books
